Some enhancements and some bugfixes - bumpt to a new Version
HaikuArchives/ScriptureGuide pull request #22
Opened 2019-12-16 09:05 UTC by Paradoxianer

This should fix #21 #20 #18 
And also improofs the search window (now shows a paragraph of the found bible text - not only the verse
You can select multiple search entrys and copy them.

2019-12-23 19:00 UTC, waddlesplash requested changes

2019-12-23 19:00 UTC, waddlesplash commented on ScriptureGuide/Makefile
> +DEFINES = DEBUG=1
Please remove these changes (i.e. enabling DEBUG and SYMBOLS.)

2019-12-23 19:00 UTC, waddlesplash commented on ScriptureGuide/Makefile
> +DEFINES = DEBUG=1
(and also DEBUGGER.)

2019-12-23 19:00 UTC, waddlesplash commented on ScriptureGuide/LogosSearchWindow.cpp
> + 			}
Please clean up the coding style in this section.

2019-12-23 19:00 UTC, waddlesplash commented on ScriptureGuide/SwordBackend.cpp
> +	printf("Searching %s in %s\n",searchText,searchstr.String());
Remove debug print

2019-12-23 19:00 UTC, waddlesplash commented on ScriptureGuideManager/MainWindow.cpp
> +			fListView->AddItem(BookRow);*/
Remote commented code

2019-12-23 19:00 UTC, waddlesplash commented on ScriptureGuideManager/Makefile
> +DEFINES = DEBUG=1
Same comments about debug here

2019-12-24 12:55 UTC, Paradoxianer commented
thanks for all the hints sorry that i forgot the debug stuff :( ... will fix them soon...  i think i will fill  a complete new Pull Request since i found time to add some more features (like sorted SGManager) and localisation.

2019-12-30 09:57 UTC, Paradoxianer reviewed
This should fixes the Codesytel violations, makefile debug setting and add a lot more features...

2020-02-13 17:32 UTC, closed without merging